### PR TITLE
Remove LSItemContentTypes

### PR DESCRIPTION
**Pull request by MaddTheSane**
LSItemContentTypes should be unique identifiers, not generic types like `public.item` or `public.data`.
This can result in the app's icons showing up in the wrong places.

Also added a category type.

### CODE REVIEW

**Comment by TomHarte** [comment]
The app's icons don't currently show up anywhere for me, frustratingly, but the reason I used generic types is that otherwise I was seeing files where the type is unknowable from the extension like `.dsk` being treated as incompatible with CLK by the Finder because some other app has a specific LSItemContentType for dsk which differs from mine.

Is there a better solution for that?

**Comment by MaddTheSane** [comment]
Other than adding all the separate UTIs into `LSItemContentTypes`?

**Comment by TomHarte** [comment]
Yeah, that's what I was trying to avoid since every other emulator seems to make up their own content types so I'd need to download all of them, now and in the future, to find out what they'd picked.

I will merge this anyway since I think the point you're making is correct: right now I'm advertising myself as saying that whatever e.g. a file named .dsk represents, I can handle it. Which is false.

Though it puts me into a position where any installed app that advertises a .dsk I don't also advertise can cause arbitrary .dsk files to become unassociated — from first hand experience, if I download something called .dsk and have two different applications that support different things called .dsk then it's even odds which will show up for 'Open With'.

**Comment by TomHarte** [comment]
Confirmed: after merging this change, the application icon in the Dock will no longer accept any of the listed files by drag and drop, and Clock Signal does not appear in the Finder's 'Open With' menu for declared file types.

So it might be incorrect to declare `public.item` etc, but the application has now definitely lost functionality. So I'll need to find the proper solution to that. I've opened it as #542

**Comment by TomHarte** [comment]
Clearly that was resolved; hopefully Clock Signal is being a better macOS citizen now.

I noticed you'd made a bunch of other improvements in your fork — please don't hesitate to offer other pull requests! I was an iOS developer for a long time, but most recently at Google while they were still in heavy denial about Swift so I've not a huge amount of practical experience there. I definitely don't mean to write obtuse code on purpose.

Regardless, thanks again for this!

**Pull request merged**
