### PR TITLE
Adds incomplete Apple IIgs emulation.

### PR DESCRIPTION
**Pull request by TomHarte**
This branch explores the feasibility of IIgs emulation, given my level of skill, the quality of documentation available and the community size. There is a non-zero chance of failure, but I'm giving it a shot.

If this succeeds, it'll knock one off #808

Other changes encapsulated:
* factors out the Apple II's auxiliary memory, language card and video switches;
* similarly factors out the real-time clock functionality from the Macintosh;
* fixes Apple II colour output in double low-res mode;
* fixes parts of the IWM that the Macintosh as I've implemented it doesn't rely on: 7Mhz mode, shifting out data when there's no recipient;
* beefs up my ever-more-useful `JustInTimeActor` template to automate use of sequence points;
* introduces the krom 65816 test cases with the LilaQ solutions (which accounts for the overwhelming majority of the heft of this pull request); and
* corrects such bugs in the 65816 as were encountered, which are too numerous to list.

Outstanding: bugs. Aplenty.

Likely reserved for future pull requests:
* SmartPort devices to support disk images that aren't floppy-sized.

### CODE REVIEW

**Comment by HelixNRG** [comment]
Hi Thomas,

I welcome any attempt at Apple IIGS emulation, especially on the Mac and especially for cycle accuracy. If you're interested, there are other emulator developers working on solutions for the IIGS talking on Slack in a specific emulators channel within an Apple II Slack workspace:

Here's where you can join:
http://apple2.gs:3000

The conversation is no nonsense and very experienced developers can give a hand where documentation may not be available.

**Comment by TomHarte** [comment]
As ongoing motivation to myself:

Screenshot 2020-11-29 at 20 02 23

**Comment by TomHarte** [comment]
Noting another milestone; currently an issue exists with exception vector selection. Putting in a quick hack around that finally allows GS/OS to boot. A proper fix will be coming shortly.

Screenshot 2020-12-08 at 07 25 23

**Comment by TomHarte** [comment]
Minor comment on this: I'm now on holiday for two weeks so that's the current cause of paused progress.

The immediate plan when I return is to complete unit tests for my current understanding of the language card, and extend those for the auxiliary switches. Between Apple's reticence for good IIgs documentation and its proclivities towards highly convoluted memory mapping, latent errors remain likely.

**Comment by TomHarte** [comment]
Review comment: per the datasheet at http://datasheets.chipdb.org/Western%20Design/w65c816s.pdf:

> 8.11 How Interrupts Affect the Program Bank and the Data Bank Registers
>
> 8.11.1 When in the Native mode, the Program Bank register (PBR) is cleared to 00 when a hardware interrupt, BRK or COP is executed. In the Native mode, previous PBR contents are automatically saved on
Stack.
>
> 8.11.2 In the Emulation mode, the PBR and DBR registers are cleared to 00 when a hardware
interrupt, BRK or COP is executed. In this case, previous contents of the PBR are not automatically saved.

Per https://github.com/TomHarte/CLK/blob/5d8f284757b7a3c6588a7d9e524f5cf358c858df/Processors/65816/Implementation/65816Implementation.hpp#L408 and having double checked against https://github.com/TomHarte/CLK/blob/AppleIIgs/Processors/65816/Implementation/65816Storage.cpp#L1099 I don't think this behaviour is implemented correctly — the data bank register is never modified, and the program bank is reset only when not in emulation mode (and neither is guaranteed already reset just because the processor is currently in emulation mode).

**Comment by TomHarte** [comment]
Status update on this, as always as much for the purposes of getting my own thoughts in order as anything else:

* the emulator is in the process of acquiring the piping necessary for instruction set-level emulations, i.e. those which are not in any way bus accurate to a specific instance of a processor, but which merely reproduce the instruction set architecture of a processor family;
* in particular the intended first use of this is the M50740/1, the IIgs's ADB controller;
* by that means I intend to use the original ROM and provide a mid-level emulation.

The instruction set infrastructure is intended to offer JIT cached decoding in the medium term and therefore the option of cached code translation (probably QEMU-style, by gluing function bodies together) in the long term. In the short term I think I'm just going to allow it to interpret as it goes until I have the full pipeline, and therefore the ADB controller, working. Steps above that are merely optimisations that I can make post hoc.

Once I believe that I have the ADB controller actually implemented to some fidelity, I will likely merge this pull request as representative of a buggy IIgs and work on individual flaws one at a time. I have a dislike for oversized branches, especially as they grow to touch more and more not-directly-correlated parts.

So then:
1. complete mid-level M50740 emulation;
2. implement ADB-bus keyboard and mouse attached to that;
3. use some of the existing working titles for at least a superficial verification;
4. merge as containing implementations of all the IIgs pieces, even if still imperfect.

A potential path forwards after (4) could be to try to pull the IIgs's implementation of a memory back into 8-bit world and replace the existing Apple II implementation. That'd buy me a lot of scope for direct comparison, and the option of running public tests such as Zellyn's, at least to test that first bank.

**Comment by TomHarte** [comment]
Possibly noteworthy: there is now an attempted implementation for all IIgs subsystems, including the ADB microcontroller and peripherals.

**Comment by TomHarte** [comment]
This pull request has become too much of a blocker on getting other things done; that's my fault for allowing it so greatly to balloon. Plan is to merge now, and deal with remaining issues piecemeal.

**Pull request merged**
