### PR TITLE
Add free function implementation of 68000 operations, and an instruction-set interpreter.

### PR DESCRIPTION
**Pull request by TomHarte**
Goes 90% of the way towards satisfying #827 except that 68000 execution logic isn't currently factored out as it is essentially duplicated in the surviving bus-accurate 68000. A subsequent pull request will resolve that.

### CODE REVIEW

**Comment by TomHarte** [comment]
> Is flow_controller.decode_conditional() already declared? (I couldn't find an implementation)

No, none of the flow controller is yet implemented, or even fully defined. I'm trying to find my way to an Intel-esque separation of bus and execution units, ideally with minimal cost, and I think I'm not there yet.

But the motivation is what you'd guess: I want to be able to use this same code for both a faster second attempt at a bus-accurate 68000, for the ST, Amiga and specific Macintoshes, and for a direct 680x0 instruction interpreter that skips bus semantics — hopefully to be substantially faster, for accelerated instances of those machines and probably as the only implementation of the 68020+ Macintoshes.

**Comment by PatrickvL** [comment]
Transferring or syncing status between the implementations would allow run time switching between M68k cores, for software that requires accurate emulation - is that part of the plan too?

Great work until now, it's really satisfying to see all parts taking shape and falling into their natural place!

**Comment by TomHarte** [comment]
> Since you declared the sp() macro to look like a function call, the resulting expression here is confusing: Normally the return value of a function call becomes a local scope variable, so performing += 2 to it without using the result, makes it look like dead code. This can be avoided by declaring the sp macro without the parenthesis (you might as well want to consider to declare it right next to the array its indexing?).

This and the TAS comment are big improvements, I think. Will do.

Otherwise status is that there's cleaning up to do, not least around the interface to what is currently `FlowController` but will get a more appropriate name if I can think of one (maybe `BusUnit` in more direct homage to x86?) but also quite a few places elsewhere, and I don't currently check for address errors or accept bus errors. I think those are the main things yet to fall into place before I can start working on separately binding `perform` to an accurate bus and usurping the current 68000 entirely.

**Comment by TomHarte** [comment]
> Should this raise a host exception, so that `run_for_instructions` can break out of its `while count > 0` loop?

Yes, you're right. For now an exception is the best way to go; when I'm in a position to profile this code in a real machine I can check out whether it makes sense to build in some other path for both address and bus errors and stops.

**Pull request merged**
