### PR TITLE
Adds emulation of the 65816.

### PR DESCRIPTION
**Pull request by TomHarte**
The 65816 has been implemented as a separate class but both it and the 6502 have a common interface; the 6502 was already templated on processor type and a new template, the 6502 selector, has been added to allow a 65816 or 6502 to be selected by the same means.

Tested via:
* hand-written Swift-based tests for all addressing modes;
* applying both Klaus Dormann's test suite and those parts of Wolfang Lorenz's that are applicable;
* use of the Jeek816 partial addressing mode tests; and
* locally, switching the Oric to use a 65802 and observing general (though not complete) software compatibility.

### CODE REVIEW

**Comment by qeeg** [comment]
For info on how the 65816 works, I'd recommend reading bsnes's source code.

**Comment by TomHarte** [comment]
Certainly an option if it comes to it, but I think I'm unblocked on the immediate uncertainty thanks to some documentation provided with the SuperCPU (a C64 upgrade). So my understanding is:
* the M flag controls accumulator and read-modify-write size;
* the X flag controls index register size; and
* emulation mode sets both of those to 8-bit and hides them from the flags register.

I'm therefore back on a positive path.

**Comment by TomHarte** [comment]
Note to myself for later: see http://6502.org/tutorials/65c816opcodes.html#5.4 to discern which 65816 addressing modes cause 16-bit read addresses to wrap within a bank and which don't.

**Comment by TomHarte** [comment]
Note to self:

If you assume that emulation status, memory and index size, and memory lock output pins are pragmatically obtained separately and want to keep `BusOperation`-esque semantics then I think the full set of operations is:

- Ready;
- IO (which can be a synonym of 'None', but should be nominally a read);
- ReadProgram;
- ReadOpcode;
- Read [Data];
- Write [Data]; and
- ReadVector.

Currently missing inputs are Ready and Abort (and if I end up not being able fully to support Abort then maybe it's not too big a deal, though it looks highly doable so that's the strong preference).

**Pull request merged**
