### PR TITLE
Decouples output of raster scans from their generation

### PR DESCRIPTION
**Pull request by TomHarte**
Specifically, so that the destination for raster scans can be supplied at runtime by the host — the standard OpenGL target can be supplied by the SDL port; an ES 2/3.x target could be written and supplied for Android or the Rapsberry Pi; a Metal target could be substituted for the Mac and iOS, etc, etc.

But, primarily, the improvements are secondary; the forced detangling allows me an opportunity to rethink:
- which information I should really be shipping to the GPU but have lost along the way; and
- the synchronisation mechanisms by which I do so.

The latter likely to affect performance and, potentially, latency.

This also hopes to open the option of having something which can draw a display but which is not classic syncs-and-diagonal-scans video. I'm specifically thinking of closed-loop LCD-type devices, which can directly address perfectly-horizontal lines.

As well as enabling #459 this is also an opportunity to reopen the door that leads to solutions for #568, #537 and #524, as well as potentially #341 (though that would suggest a little more flexibility in sound generation).

### CODE REVIEW

**Comment by TomHarte** [comment]
Update: whatever the issue is, attempting to use a composite pipeline outright crashes VMWare with 3d acceleration enabled. That may or may not turn out to be a helpful observation. It points back towards improper GL usage, possibly.

**Comment by TomHarte** [comment]
Update on this: it's getting really close now. I need to correct a regression in Oric composite output, apply some light-touch filtering to the direct RGB and monochrome paths, and deal with an issue that occasionally causes the display to blink. Also I need to test again on Linux.

Current tickets intended to be resolved directly by this pull request: just #568 and #537. While also providing the hooks necessary for #459 whenever I can next stomach it. I think step one on that road might just be an OpenGL ES3 back-end, as I dare imagine that'll be minimally different.

**Comment by TomHarte** [comment]
I've decided temporarily to accept the Oric issue as a temporary regression: it means having that platform use the default composite encoder rather than its actual colour ROM until I get that output working in its new generic form. It's very close but not quite there, but also a potential lengthy distraction.

Then there are two bugs remaining:

- occasional garbage lines and very occasional screen blanking. In both cases I think due to mishandling of the circular buffer stop condition. I've sought to go atomic/lock-free on a lot of the communications there because low-latency programming is now what I attempt to do for a living and the practice is welcome. So something to fix there.
- my virtual machine software, VMWare Fusion 10, crashes when attempting to use composite output (rather than, say, RGB). As in, the whole virtual machine goes down, sometimes causing virtual disk data loss. No useful debugging information provided, and even caveman debugging attempts are proving very slow to pursue since stdout content is lost, disk content is lost, etc. Neither Virtualbox nor Parallels offers OpenGL 3.2 support to Linux machines, and BootCamp doesn't officially support Linux. SDL refuses to create a 3.2 core profile context with Mesa. Hopefully I'll think of something. Options, extemporaneously:
  - upgrade to Fusion 11, in the hope that the bug is gone or otherwise different;
  - produce at least a skunkworks SDL/Windows kiosk-mode build, to retain at least one additional set of eyes on OpenGL usage[1], while continuing to test my local Linux build via RGB mode;
  - continue down the caveman path, trying to figure out at exactly what point I produce a version that crashes the machine.

In the meantime I've added a lot of additional state verification and OpenGL information logging to debug builds, which I don't think is a bad thing. So far only sufficiently to rule a few things out though, alas.

[1] a bug uncovered when I first started building for Linux was that a lack of care had made me accidentally assume consistent attribute binding between GLSL programs with the same fragment shader input text. Luckily that happens to work with Apple's current GLSL compiler on my particular GPU, but I was relying on undefined behaviour. I'd prefer to reduce the probability of any similar problem in the future.

**Comment by reidrac** [comment]
In case it helps, just tried the code from the PR with MSX (composite|svideo|rgb) on Linux and it looks/works fine. It feels like the startup is a little bit slower and I can see some blue horizontal lines on fullscreen in all three when the machine is starting, but then they disappear.

I can run any test you want.

This is Debian with an Intel Corporation HD Graphics 5500 (rev 09).

**Comment by TomHarte** [comment]
Fantastic, thanks for testing! I'll keep hammering away at the last few graphical errors, and call it done. I just found an issue that caused garbage lines, so hopefully that was the only such issue and now it's just black flashes left to resolve.

**Comment by TomHarte** [comment]
This pull request is now believed feature complete. Some minor regressions over the old version, but they're mostly easy fixes, and the trade is worth it — the elimination of luma aliasing makes a huge improvement to composite things that scroll horizontally but don't happen to have pixels that are one whole, one half or one quarter of a colour cycle long in their composite encoding. Notably the NTSC Master System.

So, now: a testing of all supported machines for latent issues.

**Comment by TomHarte** [comment]
Okay, so issues remaining to be resolved:

- the Atari 2600 now has an improperly-coloured border on lines with pixels (PAL and NTSC); and
- the Vic-20 produces entirely the wrong colour set in PAL mode.

Screenshots attached. Knee-jerk reactions: the Atari 2600 issue is likely some sort of poor interaction between the selected `glClearColor` and the phase/luminance video feed. From looking at a PAL colour wheel, the Vic-20 output looks like phase has been mirrored somewhere around light yellow. So possibly just an error in transcription from its former phase/luminance pairs to the new shared sort?

**Comment by TomHarte** [comment]
To confirm: a shocking four months later, I think this pull request is now feature complete. The Oric issue turns out to be slightly wider than just the one input data type, being an issue with how sub-quartile phase is handled for chroma sampling, but I'm happy to put that aside for a while so that I can deal with other pressing issues. It'll be a separate pull request that may or may not be before the next release.

So, now, probably just some light further testing, then with my usual casual disregard for consequences, back to master!

**Pull request merged**
